/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkLegalDmsRouteImport } from './routes/work.legal-dms'
import { Route as WorkEatsureRouteImport } from './routes/work.eatsure'
import { Route as WorkComplianceCompanionRouteImport } from './routes/work.compliance-companion'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkLegalDmsRoute = WorkLegalDmsRouteImport.update({
  id: '/legal-dms',
  path: '/legal-dms',
  getParentRoute: () => WorkRoute,
} as any)
const WorkEatsureRoute = WorkEatsureRouteImport.update({
  id: '/eatsure',
  path: '/eatsure',
  getParentRoute: () => WorkRoute,
} as any)
const WorkComplianceCompanionRoute = WorkComplianceCompanionRouteImport.update({
  id: '/compliance-companion',
  path: '/compliance-companion',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work': typeof WorkRouteWithChildren
  '/work/compliance-companion': typeof WorkComplianceCompanionRoute
  '/work/eatsure': typeof WorkEatsureRoute
  '/work/legal-dms': typeof WorkLegalDmsRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/compliance-companion': typeof WorkComplianceCompanionRoute
  '/work/eatsure': typeof WorkEatsureRoute
  '/work/legal-dms': typeof WorkLegalDmsRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work': typeof WorkRouteWithChildren
  '/work/compliance-companion': typeof WorkComplianceCompanionRoute
  '/work/eatsure': typeof WorkEatsureRoute
  '/work/legal-dms': typeof WorkLegalDmsRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work'
    | '/work/compliance-companion'
    | '/work/eatsure'
    | '/work/legal-dms'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work/compliance-companion'
    | '/work/eatsure'
    | '/work/legal-dms'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/work'
    | '/work/compliance-companion'
    | '/work/eatsure'
    | '/work/legal-dms'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/legal-dms': {
      id: '/work/legal-dms'
      path: '/legal-dms'
      fullPath: '/work/legal-dms'
      preLoaderRoute: typeof WorkLegalDmsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/eatsure': {
      id: '/work/eatsure'
      path: '/eatsure'
      fullPath: '/work/eatsure'
      preLoaderRoute: typeof WorkEatsureRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/compliance-companion': {
      id: '/work/compliance-companion'
      path: '/compliance-companion'
      fullPath: '/work/compliance-companion'
      preLoaderRoute: typeof WorkComplianceCompanionRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkComplianceCompanionRoute: typeof WorkComplianceCompanionRoute
  WorkEatsureRoute: typeof WorkEatsureRoute
  WorkLegalDmsRoute: typeof WorkLegalDmsRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkComplianceCompanionRoute: WorkComplianceCompanionRoute,
  WorkEatsureRoute: WorkEatsureRoute,
  WorkLegalDmsRoute: WorkLegalDmsRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
