/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as WorkRouteImport } from './routes/work'
import { Route as VisualsRouteImport } from './routes/visuals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkLegalDmsRouteImport } from './routes/work.legal-dms'
import { Route as WorkEatsureRouteImport } from './routes/work.eatsure'
import { Route as WorkComplianceCompanionRouteImport } from './routes/work.compliance-companion'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualsRoute = VisualsRouteImport.update({
  id: '/visuals',
  path: '/visuals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLegalDmsRoute = WorkLegalDmsRouteImport.update({
  id: '/legal-dms',
  path: '/legal-dms',
  getParentRoute: () => WorkRoute,
} as any)
const WorkEatsureRoute = WorkEatsureRouteImport.update({
  id: '/eatsure',
  path: '/eatsure',
  getParentRoute: () => WorkRoute,
} as any)
const WorkComplianceCompanionRoute = WorkComplianceCompanionRouteImport.update({
  id: '/compliance-companion',
  path: '/compliance-companion',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/visuals': typeof VisualsRoute
  '/work': typeof WorkRouteWithChildren
  '/writing': typeof WritingRoute
  '/work/compliance-companion': typeof WorkComplianceCompanionRoute
  '/work/eatsure': typeof WorkEatsureRoute
  '/work/legal-dms': typeof WorkLegalDmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/visuals': typeof VisualsRoute
  '/work': typeof WorkRouteWithChildren
  '/writing': typeof WritingRoute
  '/work/compliance-companion': typeof WorkComplianceCompanionRoute
  '/work/eatsure': typeof WorkEatsureRoute
  '/work/legal-dms': typeof WorkLegalDmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/visuals': typeof VisualsRoute
  '/work': typeof WorkRouteWithChildren
  '/writing': typeof WritingRoute
  '/work/compliance-companion': typeof WorkComplianceCompanionRoute
  '/work/eatsure': typeof WorkEatsureRoute
  '/work/legal-dms': typeof WorkLegalDmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/visuals'
    | '/work'
    | '/writing'
    | '/work/compliance-companion'
    | '/work/eatsure'
    | '/work/legal-dms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/visuals'
    | '/work'
    | '/writing'
    | '/work/compliance-companion'
    | '/work/eatsure'
    | '/work/legal-dms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/visuals'
    | '/work'
    | '/writing'
    | '/work/compliance-companion'
    | '/work/eatsure'
    | '/work/legal-dms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  VisualsRoute: typeof VisualsRoute
  WorkRoute: typeof WorkRouteWithChildren
  WritingRoute: typeof WritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visuals': {
      id: '/visuals'
      path: '/visuals'
      fullPath: '/visuals'
      preLoaderRoute: typeof VisualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/legal-dms': {
      id: '/work/legal-dms'
      path: '/legal-dms'
      fullPath: '/work/legal-dms'
      preLoaderRoute: typeof WorkLegalDmsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/eatsure': {
      id: '/work/eatsure'
      path: '/eatsure'
      fullPath: '/work/eatsure'
      preLoaderRoute: typeof WorkEatsureRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/compliance-companion': {
      id: '/work/compliance-companion'
      path: '/compliance-companion'
      fullPath: '/work/compliance-companion'
      preLoaderRoute: typeof WorkComplianceCompanionRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkComplianceCompanionRoute: typeof WorkComplianceCompanionRoute
  WorkEatsureRoute: typeof WorkEatsureRoute
  WorkLegalDmsRoute: typeof WorkLegalDmsRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkComplianceCompanionRoute: WorkComplianceCompanionRoute,
  WorkEatsureRoute: WorkEatsureRoute,
  WorkLegalDmsRoute: WorkLegalDmsRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  VisualsRoute: VisualsRoute,
  WorkRoute: WorkRouteWithChildren,
  WritingRoute: WritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
